### ISSUE TITLE
実行時エラー

### ISSUE THREAD

**Issue by nag8** [nag8/getBookFromLibrary#1]
ken@MyComputer /m/c/U/k/D/G/getBookFromLibrary> python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
ken@MyComputer /m/c/U/k/D/G/getBookFromLibrary> python main.py
  File "main.py", line 6
SyntaxError: Non-ASCII character '\xe8' in file main.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by nag8** [comment]
バグfix
